#!/bin/bash
# Fix ALSA default device to point to USB Audio adapter
# Usage: sudo bash fix_audio_default.sh
# Safe to run on any treatbot — auto-detects USB card number

CARD=$(grep "USB-Audio" /proc/asound/cards 2>/dev/null | head -1 | grep -oP '^\s*\K[0-9]+')

if [ -z "$CARD" ]; then
    echo "ERROR: No USB Audio device found in /proc/asound/cards"
    cat /proc/asound/cards
    exit 1
fi

echo "Found USB Audio on card $CARD"

cat > /etc/asound.conf << EOF
# Auto-generated by fix_audio_default.sh
# Points ALSA default device to USB Audio adapter (card $CARD)
defaults.pcm.card $CARD
defaults.ctl.card $CARD
EOF

echo "Wrote /etc/asound.conf (card $CARD)"
echo "Restart treatbot: sudo systemctl restart treatbot"
